server:
  port: 1334
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/kronos?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
#    generate-ddl: true
  mail:
    host: smtp.yunzongnet.com
    username: zhifu@yunzongnet.com
    password: 4HwxfI7b
    port: 994
    protocol: smtps
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379

kronos:
  enable: true
  service-api: http://123.57.137.193:6443
  image-pull-policy: IfNotPresent
  restart-policy: Never
  group-name: batch
  api-version: v1
  log-path: /data/application/logs/kronos/
  resync-period-in-millis: 60000
