server:
  port: 12710
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://10.200.46.238:3306/kronos?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

redisson:
  sentinel:
    masterName: paygate
    sentinelAddresses:
      - redis://ds.redis3-1.yunzong:26379
      - redis://ds.redis3-2.yunzong:26379
      - redis://ds.redis3-3.yunzong:26379

kronos:
  enable: true
  service-api: http://10.200.46.239:8080
  image: executor:statement
  image-pull-policy: IfNotPresent
  restart-policy: Never
  group-name: batch
  api-version: v1
  log-path: /data/application/logs/kronos/
  resync-period-in-millis: 60000

